### ISSUE TITLE
Use on custom irregular time series

### ISSUE THREAD

**Issue by TNA8** [sheoyon-jhin/ANCDE#1]
Thanks for your sharing of this great work.

I have an irregular multivariant time series. Intervals of observations are very irregular. I want to make a multi step forecasting model.
I tried to use some imputation methods for missing values, but the accuracy was very poor.
Finally I have found that your approach could be helpful to my case.

I think my dataset is very similar to your google stock dataset.

* To use your model for my dataset, what steps should I follow?
* Is it possible to use your model for `multi-step` forecasting? If then, how can I make it?

Thanks in advance.

**Comment by sheoyon-jhin** [comment]
At first, I recommend preprocessing your data with the code  "stock.py" in ./experiments/datasets/.
Then, use "stock.py" in ./experiments/ to run ANCDE.
FYI, we used 
`python3 stock.py --seed 2021 --input_seq 20 --output_seq 5 --model="ancde_forecasting" --h_channel 12 --hh_channel 12 --layer 2 --lr 0.001 --soft '' --slope_check 'True' --timewise '' --attention_channel 4 --attention_attention_channel 8 --step_mode 'valloss'`
to run code "stock.py".
You can edit your command based on this form.

Also, we added multi-step forecasting today, so It would be nice to check our code!

**Comment by TNA8** [comment]
Thanks for your detailed explanation.
Another question about irregular time series.
According to  above command, we will use last 20 sequences to predict next 5 sequences.
Those 20 sequences is for irregular timestamps as you know.
In that case, which timestamps is the output 5 sequences for?

For example, let's suppose that time stamps for the 20 input sequnce: [2020-01-01, 2020-01-05, 2020-02-01, ..., 2020-07-08] (Note: time intervals are not constant). If we predict with those sequences, we will have 5 sequences.
I can't know those time index for those 5 sequences. Is it [2020-07-09, 2020-07-10, 2020-07-11, 2020-07-12, 2020-07-13] with constant interval?

I saw your data has no time index. How can I understand it?

Thanks.

**Comment by Karlheinzniebuhr** [comment]
@TNA8 would you mind sharing how you got this running? I'm getting this exception [https://github.com/sheoyon-jhin/ANCDE/issues/5](https://github.com/sheoyon-jhin/ANCDE/issues/5 )
